import { writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(root, "src/assets/fonts");
const cssOut = resolve(root, "src/assets/fonts.css");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// ascent/descent/lineGap are percentages of font-size derived from each font's
// hhea table metrics, normalising the cross-platform discrepancy between macOS
// (hhea) and Windows (OS/2 win/typo) vertical metrics.
const fonts = [
  {
    file: "kiwi-maru-400.woff2",
    url: "https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@400&display=swap&text=北海道札幌函館旭川室蘭苫小牧釧路知床帯広見青森県弘前八戸岩手盛岡平泉宮城仙台秋田山形庄内福島会津郡白河いわき茨水土浦つくば栃木宇都那須とちぎ群馬橋高崎埼玉大口所沢越熊谷春日部千葉成習志野市船袖ヶ原柏松東京品世練杉並板足立江葛飾王子多摩神奈横浜湘南相模梨富士新潟長上本諏訪石金井岐阜飛騨静沼伊豆愛名古屋豊三尾張一重鈴鹿四勢滋賀府阪なに和堺良鳥歌兵庫姫取根嶋出雲倉敷下関徳香媛九州久留米筑佐保分児奄美沖縄繩",
    ascent: "116%",
    descent: "28.8%",
    lineGap: "0%",
  },
  {
    file: "kiwi-maru-500.woff2",
    url: "https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@500&display=swap&text=北海道札幌函館旭川室蘭苫小牧釧路知床帯広見青森県弘前八戸岩手盛岡平泉宮城仙台秋田山形庄内福島会津郡白河いわき茨水土浦つくば栃木宇都那須とちぎ群馬橋高崎埼玉大口所沢越熊谷春日部千葉成習志野市船袖ヶ原柏松東京品世練杉並板足立江葛飾王子多摩神奈横浜湘南相模梨富士新潟長上本諏訪石金井岐阜飛騨静沼伊豆愛名古屋豊三尾張一重鈴鹿四勢滋賀府阪なに和堺良鳥歌兵庫姫取根嶋出雲倉敷下関徳香媛九州久留米筑佐保分児奄美沖縄繩",
    ascent: "116%",
    descent: "28.8%",
    lineGap: "0%",
  },
  {
    file: "biz-udpmincho-700.woff2",
    url: "https://fonts.googleapis.com/css2?family=BIZ+UDPMincho:wght@700&display=swap&text=さすせそたちつてとなにぬねのはひふほまみむめもやゆよらりるろれわあいうえかきくけこをおが",
    ascent: "87.99%",
    descent: "12.01%",
    lineGap: "0%",
  },
  {
    file: "lexend-giga-600.woff2",
    url: "https://fonts.googleapis.com/css2?family=Lexend+Giga:wght@600&display=swap&text=YAKMGHE",
    ascent: "100%",
    descent: "25%",
    lineGap: "0%",
  },
];

mkdirSync(outDir, { recursive: true });

const blocks = [];

for (const font of fonts) {
  process.stdout.write(`Downloading ${font.file}... `);

  const cssRes = await fetch(font.url, { headers: { "User-Agent": UA } });
  if (!cssRes.ok) throw new Error(`Google Fonts CSS fetch failed: ${cssRes.status}`);
  const css = await cssRes.text();

  const woff2Url = css.match(/url\((https:\/\/[^)]+)\)/)?.[1];
  if (!woff2Url) throw new Error(`No woff2 URL found in response for ${font.file}`);

  const fontRes = await fetch(woff2Url, { headers: { "User-Agent": UA } });
  if (!fontRes.ok) throw new Error(`Font file fetch failed: ${fontRes.status}`);
  const buffer = Buffer.from(await fontRes.arrayBuffer());

  writeFileSync(resolve(outDir, font.file), buffer);
  console.log(`${(buffer.length / 1024).toFixed(1)} KB`);

  const overrides = `  ascent-override: ${font.ascent};\n  descent-override: ${font.descent};\n  line-gap-override: ${font.lineGap};`;
  const block = css
    .replace(/url\(https:\/\/[^)]+\)/, `url("./fonts/${font.file}")`)
    .replace(/\}/, `${overrides}\n}`);
  blocks.push(block.trim());
}

const output = `/* Generated by scripts/download-fonts.mjs — do not edit by hand.
   Run \`npm run fonts\` to refresh fonts and regenerate this file. */

${blocks.join("\n\n")}
`;

writeFileSync(cssOut, output);
console.log(`Written fonts.css`);
